kind: ConfigMap
metadata:
  name: ipfs-config
apiVersion: v1
data:
  init.sh: |-
    #!/bin/sh
    set -e
    set -x

    # First start with current persistent volume
    [ -f $IPFS_PATH/version ] || {
      echo "No ipfs repo found in $IPFS_PATH. Initializing..."
      # Replaces the entrypoint script https://github.com/ipfs/go-ipfs/blob/master/bin/container_daemon
      # but without the su-exec stuff that gets denied in k8s
      ipfs init
      ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
      ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080
      ipfs config Addresses

      echo "Removing all bootstrap nodes..."
      echo "(see https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks)"
      ipfs bootstrap rm --all
    }

    exit 0


  peers-kubernetes-refresh.sh: |-
    #!/bin/sh
    set -e
    set -x

    echo "Let's assume for now that pods will find each other,"
    echo "i.e. no need for ipfs bootstrap (using podIPs from kube API calls)"
    exit 0
    