apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5001
      targetPort: api
      protocol: TCP
      name: http
    - port: 8080
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: 4001
      targetPort: swarm
      protocol: TCP
      name: swarm
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
