apiVersion: v1
kind: Service
metadata:
  name: swarm-{{ .Values.service.name }}
  annotations:
      external-dns.alpha.kubernetes.io/hostname: ipfs.melandworld.com
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: swarm
      protocol: TCP
      name: swarm
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
