name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish Helm chart
        uses: Meland-Inc/helm-gh-pages@master
        with:
          charts_url: https://meland-inc.github.io/ipfs-charts-repository/
          repository: ipfs-charts-repository
          branch: gh-pages
          charts_dir: charts
          token: ${{ secrets.BOT_GITHUB_TOKEN }}