name: DEBUG Charts

on:
  push:
    branches:
      - chore/github-actions-add-build-charts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish Helm chart
        uses: Meland-Inc/helm-gh-pages@master
        with:
          charts_url: https://meland-inc.github.io/charts/
          repository: charts
          branch: gh-pages
          charts_dir: charts
          token: ${{ secrets.BOT_GITHUB_TOKEN }}